### ISSUE TITLE
I got the tweak compiled but now it makes the app crash when I go to yt settings 

### ISSUE THREAD

**Issue by dobby1970** [PoomSmart/YTDarker#2]
the new yt version 17.20.3 crashes when I press on the profile icon when i wanna go to the settings
when I look trough the crash logs on my iOS device its showing this tweak as a reason it crashed! while it's was working on the previous version!

**Comment by PoomSmart** [comment]
Do you have the crash log?

**Comment by PoomSmart** [comment]
Fixed in the latest commit.
